CS2113-AY1819S1-T16-1/main

docs/DeveloperGuide.adoc

Ported the following sections to the Developer Guide
- User stories (Module Management)
- Use cases (Module Management)

Updated the Developer Guide with my portion

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

**dev guide** 
- use cases for module management
- user stories for module management
**user guide** 
- made a few changes to reflect project direction

updated dev guide and user guide

---

docs/DeveloperGuide.adoc

Added user stories and use cases for the 'Notes Management' feature in DeveloperGuide.adoc file.

Updated DeveloperGuide.adoc file

---

docs/UserGuide.adoc

Updates the userguide document with class management portion

Added Class Management to user guide document

---

docs/UserGuide.adoc

fixed minor punctuation error as well

Updated user doc with commands summary for Class Management

---

docs/AboutUs.adoc
docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Organised the subheadings and added appropriate information of my part [gradebook management].

Updated AboutUs, UserGuide and DeveloperGuide

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

User Guide
- Corrected the title from "Developer Guide" to "User Guide"
- Changed "Example(s)" to "Examples" in Notes Management section to be consistent with the other features
- Added notes management feature in command summary section
Developer Guide
- Added one user story and one use case for notes management feature (Finding notes)

Updated User Guide and Developer Guide

---

src/main/java/seedu/address/model/classroom/ClassModule.java
src/main/java/seedu/address/model/classroom/ClassName.java
src/main/java/seedu/address/model/classroom/Enrollment.java

* Bug fix with xml element not showing up after making fields private

Minor bug fix with xml elements

---

src/main/java/seedu/address/logic/commands/ClassListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/classroom/Classroom.java
src/main/java/seedu/address/model/classroom/Enrollment.java
src/test/java/seedu/address/logic/commands/ClassCreateCommandTest.java

* Added class listing
* camelCased the xml element name for classroom
* fix variable naming
* added one basic test

Added class listing feature with minor bug fix

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Addresses https://github.com/CS2113-AY1819S1-T16-1/main/issues/72

Updated relevant document with the class listing feature.

---

src/main/java/seedu/address/model/StorageController.java
src/main/java/seedu/address/model/gradebook/Gradebook.java
src/main/java/seedu/address/model/gradebook/GradebookManager.java

Made changes only to Gradebook add command according to Yuan Cai's feedback

Updated Gradebook Add Command

---

src/main/java/seedu/address/logic/commands/GradebookListCommand.java
src/main/java/seedu/address/model/gradebook/Gradebook.java
src/main/java/seedu/address/model/gradebook/GradebookManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedGradebook.java

Made changes according to Yuan Cai's feedback

Updated Gradebook List

---

src/main/java/seedu/address/logic/commands/ClassListCommand.java
src/main/java/seedu/address/model/classroom/Classroom.java

by rendering the strings as html

Enhanced class listing view

---

docs/DeveloperGuide.adoc

* Fix wrongly placed document section

developerguide.adoc update fix for wrongly placed section

---

src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
src/main/java/seedu/address/logic/commands/GradebookListCommand.java
src/main/java/seedu/address/model/gradebook/Gradebook.java
src/main/java/seedu/address/model/gradebook/GradebookManager.java

Updated Gradebook Find Command

---

src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
src/main/java/seedu/address/logic/commands/NoteEditCommand.java
src/main/java/seedu/address/logic/commands/NoteListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
src/main/java/seedu/address/logic/parser/NoteListCommandParser.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/ui/NoteEntryPrompt.java
src/main/java/seedu/address/ui/NoteTextEditWindow.java
src/test/java/seedu/address/logic/commands/NoteAddCommandTest.java
src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
src/test/java/seedu/address/model/note/NoteManagerTest.java
src/test/java/seedu/address/testutil/NoteBuilder.java

New feature: `note edit INDEX [m/MODULE_CODE] [d/DATE]`
- Edits an existing note by `INDEX`
- Opens a TextArea window to edit the specified note.
Tests
- Added JUnit tests for Notes Management feature.
This PR resolves #138

Added support to edit notes by index

---

src/main/java/seedu/address/logic/commands/ClassAddCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
src/main/java/seedu/address/logic/commands/ClassListCommand.java
src/main/java/seedu/address/logic/parser/ClassAddCommandParser.java
src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ClassroomParserUtil.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/classroom/ClassModule.java
src/main/java/seedu/address/model/classroom/ClassName.java
src/main/java/seedu/address/model/classroom/Classroom.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/model/classroom/Enrollment.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
src/test/java/seedu/address/model/classroom/ClassModuleTest.java
src/test/java/seedu/address/model/classroom/ClassNameTest.java
src/test/java/seedu/address/model/classroom/ClassroomTest.java
src/test/java/seedu/address/model/classroom/EnrollmentTest.java
src/test/java/seedu/address/testutil/ClassroomBuilder.java
src/test/java/seedu/address/testutil/TypicalClassrooms.java

* Changed `ClassroomManager` to use singleton implementation and corresponding code change to classes that uses them
* Added duplicate checks to classroom adding
* Added validation checks to class add, delete
* Shifted class prefix into template
* Weaker notion of equality is added
* More extensive test added
* `ClassroomBuilder` and `TypicalClassrooms` for corresponding tests

Code enhancements - Validation for class-related commands

---

src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
src/main/java/seedu/address/logic/commands/GradebookFindCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/GradebookDeleteCommandParser.java
src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
src/main/java/seedu/address/logic/parser/GradebookFindCommandParser.java
src/main/java/seedu/address/model/gradebook/Gradebook.java
src/main/java/seedu/address/model/gradebook/GradebookManager.java

- updated gradebook add command

Gradebook Edit Command Implemented

---

src/main/java/seedu/address/logic/commands/ClassEditCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassEditCommandParser.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/163
* Implemented Classroom editing feature

Added implementation for Classroom editing

---

src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/classroom/Classroom.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/105
* Changed prefix of classname to be 'cn/'
* Classroom now keeps track of list of students assigned to the classroom
* Duplication check for assignment of students to the same classroom

Added implementation for assigning student to classroom

---

src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
src/main/java/seedu/address/logic/commands/NoteEditCommand.java
src/main/java/seedu/address/logic/commands/NoteListCommand.java
src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
src/main/java/seedu/address/model/note/Note.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
src/main/java/seedu/address/ui/HtmlCardProcessor.java
src/main/java/seedu/address/ui/NoteEntryPrompt.java
src/main/resources/view/NoteEntryPromptWindow.fxml
src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
src/test/java/seedu/address/model/note/NoteManagerTest.java
src/test/java/seedu/address/testutil/NoteBuilder.java

- List of notes is now displayed in the WebView panel instead of the TextArea result display box.
- Created a utility HTML card processor class which helps to render cards in the WebView using HTML language.
- Updates the list when there is a change in the note dataset.
Resolves #182

Note list is displayed in WebView panel

---

src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
src/test/java/seedu/address/logic/commands/GradebookDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
src/test/java/seedu/address/logic/parser/GradebookEditCommandParserTest.java

- added necessary test for gradebook edit command

Updated Gradebook Edit Command

---

src/main/java/seedu/address/logic/commands/ClassAddCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassEditCommand.java
src/main/java/seedu/address/logic/commands/ClassListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassAddCommandParser.java
src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
src/main/java/seedu/address/logic/parser/ClassDeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ClassDeleteStudentCommandParser.java
src/main/java/seedu/address/logic/parser/ClassEditCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/classroom/Classroom.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/172 
and
Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/173
* Implemented unassign student from classroom feature
* Modified constant prefix to follow OSS guidelines
* Fix boolean method name to follow OSS guidelines (isXxx)
* Modified class listing to include students assigned
Also contains changes based on minor comments

Added implementation to unassign student from classroom

---

src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassAddStudentAttendanceCommandParser.java
src/main/java/seedu/address/logic/parser/ClassAddStudentCommandParser.java
src/main/java/seedu/address/model/StorageController.java
src/main/java/seedu/address/model/classroom/Attendance.java
src/main/java/seedu/address/model/classroom/Classroom.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java
src/main/java/seedu/address/storage/serializable/XmlSerializableClassroomAttendanceList.java
src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java
src/test/java/seedu/address/logic/commands/ClassDeleteCommandTest.java
src/test/java/seedu/address/logic/parser/ClassAddCommandParserTest.java
src/test/java/seedu/address/model/classroom/ClassNameTest.java
src/test/java/seedu/address/model/classroom/ClassroomTest.java
src/test/java/seedu/address/testutil/ClassroomBuilder.java
src/test/java/seedu/address/testutil/TypicalClassrooms.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/192
* Made changes to corresponding files for class attendance
…the given day
Also include:
Checkstyle fix for java tests/testutils
some minor comment resolution

Implemented marking of student attendance

---

src/main/java/seedu/address/logic/commands/ClassAddCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassEditCommand.java
src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassListStudentAttendanceCommandParser.java
src/main/java/seedu/address/model/classroom/Attendance.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/195
* Implemented class attendance listing  …
* Added support to read from `XmlAdaptedClassroomAttendance` and store them correspondingly for the classroom

Added implementation for classroom attendance

---

src/main/java/seedu/address/logic/commands/GradeAddCommand.java
src/main/java/seedu/address/logic/commands/GradeGraphCommand.java
src/main/java/seedu/address/logic/commands/GradeListCommand.java
src/main/java/seedu/address/logic/commands/GradebookAddCommand.java
src/main/java/seedu/address/logic/commands/GradebookDeleteCommand.java
src/main/java/seedu/address/logic/commands/GradebookEditCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/GradeAddCommandParser.java
src/main/java/seedu/address/logic/parser/GradeGraphCommandParser.java
src/main/java/seedu/address/logic/parser/GradebookAddCommandParser.java
src/main/java/seedu/address/logic/parser/GradebookEditCommandParser.java
src/main/java/seedu/address/model/StorageController.java
src/main/java/seedu/address/model/gradebook/GradebookManager.java
src/main/java/seedu/address/model/grades/Grades.java
src/main/java/seedu/address/model/grades/GradesManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedGradebook.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedGrades.java
src/main/java/seedu/address/storage/serializable/XmlSerializableGradeList.java
src/main/java/seedu/address/ui/GradeGraphDisplay.java
src/test/java/seedu/address/logic/commands/GradeAddCommandTest.java
src/test/java/seedu/address/logic/commands/GradebookEditCommandTest.java
src/test/java/seedu/address/logic/parser/GradeAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/GradebookAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/GradebookDeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/GradebookFindCommandParserTest.java

This PR consists of:
1. Grade feature implementation
- grade add
- grade list
- grade graph
2. Removed outdated test due to modification of codes
Will include tests in the future PR.

Implemented Grade feature

---

src/main/java/seedu/address/logic/commands/ClassAddCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassEditCommand.java
src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ClassDeleteStudentAttendanceCommandParser.java
src/main/java/seedu/address/logic/parser/ClassListStudentAttendanceCommandParser.java
src/main/java/seedu/address/model/classroom/Attendance.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/196
PR should be pulled after https://github.com/CS2113-AY1819S1-T16-1/main/pull/202
* Added class attendance modification (removal of marked attendance of student)
* Now throw new CommandException instead of returning new CommandResult is specific class related results are null

 Added implementation for classroom attendance modification

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/commands/NoteEditCommand.java
src/main/java/seedu/address/logic/commands/NoteExportCommand.java
src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/note/Note.java
src/main/java/seedu/address/model/note/NoteDate.java
src/main/java/seedu/address/model/note/NoteLocation.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/model/note/NoteText.java
src/main/java/seedu/address/model/note/NoteTime.java
src/main/java/seedu/address/model/note/NoteTitle.java
src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
src/main/java/seedu/address/ui/BrowserPanel.java
src/main/java/seedu/address/ui/HtmlCardProcessor.java
src/main/java/seedu/address/ui/NoteEntryPrompt.java
src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteExportCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
src/test/java/seedu/address/model/note/NoteManagerTest.java
src/test/java/seedu/address/testutil/NoteBuilder.java

- Added data validation to Notes.
- The WebView page can now automatically scroll to the bottom when the Note list page is loaded.
- Able to check if the current loaded WebView page is the note list.
- Updated relevant test codes and created tests for Note Export Command.

Added data validation to note attributes

---

src/main/java/seedu/address/logic/commands/CourseAddCommand.java
src/main/java/seedu/address/logic/commands/DebugCommand.java
src/main/java/seedu/address/logic/commands/StudentAddCommand.java
src/main/java/seedu/address/logic/commands/StudentListCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/StorageController.java
src/main/java/seedu/address/model/course/CourseCode.java
src/main/java/seedu/address/model/course/CourseName.java
src/main/java/seedu/address/model/student/StudentManager.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/CourseAddCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
src/test/java/seedu/address/logic/parser/StudentAddCommandParserTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

* Improved validation for course and students (max character limits, no duplicate matric no(s))
* Student List will display student' course details
* Added/fixed tests pertaining to the above.
Resolves #155

Improved validation for course and students. Added testMode for Storage Controller.

---

src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/commands/NoteDeleteCommand.java
src/main/java/seedu/address/logic/commands/NoteEditCommand.java
src/main/java/seedu/address/logic/commands/NoteFindCommand.java
src/main/java/seedu/address/logic/commands/NoteListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/NoteFindCommandParser.java
src/main/java/seedu/address/logic/parser/NoteListCommandParser.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/ui/BrowserPanel.java
src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java

- `note find` finds notes using one or more keyword(s).
- It searches for matches in a Note object's `title` and `noteText` fields.
- Updated some test codes and created new tests for the new command.
Resolves #204

New feature note find

---

src/main/java/seedu/address/logic/commands/ClassAddCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassEditCommand.java
src/main/java/seedu/address/logic/commands/ClassListCommand.java
src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroom.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedClassroomAttendance.java
src/test/java/seedu/address/logic/commands/ClassAddCommandTest.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/197
* Added validations to user input for class-related commands
*  Extra validation check when importing xml data into memory, will skip invalid/nonexisting data

Added validations to user input for class-related commands

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

* Update UG and DG respectively for corresponding changes

Update of UG and DG

---

src/main/java/seedu/address/model/classroom/ClassroomManager.java

* Handles removal of module by module code and removal of student by matricNo
usage example: 
```
`ClassroomManager` classroomManager = ClassroomManager.getInstance();
classroomManager.handleModuleDeletedByModuleCode(targetModuleCode);
classroomManager.handleStudentDeletedByMatricNo(personToDelete.getMatricNo().matricNo);
```

* Handles removal of module and removal of student

---

docs/UserGuide.adoc

Fix userguide

---

docs/UserGuide.adoc

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/276

Update UG to fix error in documentation

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

* swapped course management and student management. 
* removed access to undo, redo and clear commands.
* removed several tests pertaining to undo, redo and clear commands.
Resolves #264 #261 #260 #266

Rectified issues found in PE1

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc
docs/team/tristyxxnana.adoc

first draft for project portfolio page.

Project Portfolio Page

---

src/main/java/seedu/address/logic/commands/ClassAddStudentCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentCommand.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/289

Validates whether a student is enrolled into a module before assigning the student to classroom

---

src/main/java/seedu/address/logic/parser/NoteDeleteCommandParser.java
src/test/java/seedu/address/logic/parser/NoteDeleteCommandParserTest.java

- Updated relevant test codes.

Removed validation for duplicate indexes for faster execution

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

* Fix formatting error in user guide and developer guide

Fix documentation error in user guide and developer guide

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/model/note/NoteText.java
src/main/java/seedu/address/storage/adapter/CsvAdaptedNote.java
src/main/java/seedu/address/storage/adapter/XmlAdaptedNote.java
src/main/java/seedu/address/ui/NoteEntryPrompt.java
src/test/java/seedu/address/logic/commands/NoteDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/NoteEditCommandTest.java
src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java
src/test/java/seedu/address/logic/commands/NoteFindCommandTest.java
src/test/java/seedu/address/logic/commands/NoteListCommandTest.java
src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteFindCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteListCommandParserTest.java
src/test/java/seedu/address/model/note/NoteManagerTest.java

`note add` now allows creation of notes without assigning it to a module.
Increased character limit of notes from 150 to 300.
Improved validation when reading notes from XML.
- IllegalArgumentException and NullPointerException will be handled so that notes containing invalid values in XML will not be added to the Note Model upon start up. Valid data will still be loaded.
- Errors found in the XML will be logged in the terminal, hence not visible to user.
Updated relevant test codes

Set MODULE_CODE as optional parameter when creating notes..

---

src/main/java/seedu/address/commons/util/CsvUtil.java
src/main/java/seedu/address/logic/commands/NoteExportCommand.java
src/main/java/seedu/address/model/note/NoteManager.java
src/test/java/seedu/address/logic/commands/NoteExportCommandTest.java

- Changed path for exported CSV files to {Trajectory dir}/data/CSVexport/
- `note export` now shows the created file's location to the user upon successful command execution.
- Added logging for CsvUtil. Adjusted some JavaDoc comments.
- Refactored codes for NoteExportCommand.
- Updated tests for NoteExportCommandTest.
Resolves #255

Changed directory of exported CSV files

---

src/main/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommand.java
src/main/java/seedu/address/logic/commands/ClassListStudentAttendanceCommand.java
src/main/java/seedu/address/model/classroom/ClassroomManager.java
src/test/java/seedu/address/logic/commands/ClassAddStudentAttendanceCommandTest.java
src/test/java/seedu/address/logic/commands/ClassDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/ClassDeleteStudentAttendanceCommandTest.java
src/test/java/seedu/address/logic/commands/ClassDeleteStudentCommandTest.java
src/test/java/seedu/address/logic/commands/ClassEditCommandTest.java
src/test/java/seedu/address/logic/commands/ClassListStudentAttendanceCommandTest.java
src/test/java/seedu/address/logic/parser/ClassAddStudentAttendanceCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClassAddStudentCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClassDeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClassDeleteStudentAttendanceCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClassDeleteStudentCommandParserTest.java
src/test/java/seedu/address/logic/parser/ClassListStudentAttendanceCommandParserTest.java

Resolves https://github.com/CS2113-AY1819S1-T16-1/main/issues/329
* Added test files for the rest of the class related commands
* Removed some redundant code in test files
* Fix logic error for test case for classroom attendance

Added more test cases for class related features

---

src/main/java/seedu/address/logic/commands/NoteAddCommand.java
src/main/java/seedu/address/logic/commands/NoteEditCommand.java
src/main/java/seedu/address/logic/parser/NoteAddCommandParser.java
src/main/java/seedu/address/logic/parser/NoteEditCommandParser.java
src/test/java/seedu/address/logic/parser/NoteAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/NoteEditCommandParserTest.java

Added validation if module exists when adding notes to module.

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/CourseAddCommand.java
src/main/java/seedu/address/logic/commands/CourseDeleteCommand.java
src/main/java/seedu/address/model/course/Course.java
src/main/java/seedu/address/model/course/FacultyName.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/CourseAddCommandParserTest.java
src/test/java/seedu/address/logic/parser/CourseDeleteCommandParserTest.java
src/test/java/seedu/address/model/course/CourseCodeTest.java
src/test/java/seedu/address/model/course/CourseNameTest.java
src/test/java/seedu/address/model/course/FacultyNameTest.java
src/test/java/seedu/address/testutil/CourseBuilder.java

Signed-off-by: m-aslam-mj2 <e0176811@u.nus.edu>

Added a few tests.

---

src/main/java/seedu/address/model/classroom/ClassroomManager.java

* Changed display of class related info to banner type

Changed display of class related info to banner type

---

src/main/java/seedu/address/logic/commands/NoteListCommand.java
src/main/java/seedu/address/model/note/NoteManager.java
src/main/java/seedu/address/ui/HtmlCardProcessor.java

- Note cards are now displayed in columns.

Updated the rendering of HTML cards for notes

---

src/main/java/seedu/address/logic/commands/DebugCommand.java

* Populated `DebugCommand` with sample data

Populate sample data

---

build.gradle
docs/DeveloperGuide.adoc
docs/UserGuide.adoc
src/main/java/seedu/address/model/student/StudentManager.java
src/test/java/seedu/address/logic/commands/StudentAddCommandIntegrationTest.java

Signed-off-by: m-aslam-mj2 <e0176811@u.nus.edu>

Updated student list view. Updated UG and DG. Updated build.gradle.
